<a href="https://colab.research.google.com/github/yoohw0317/DAP__/blob/main/lecture2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

np.random.seed(0)

# NumPy Exercises!
Complete the solution code to have a desired output.

**[Caution!]** Not allow to use iteration, such as for-loop.





### 1. Create a 4×4 numpy array of all True boolean’s 

In [2]:
# Input
arr_size = (4, 4)

# Solution
bool_arr = np.full(arr_size, True, bool)

# Print
print(bool_arr)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


### 2. Extract all odd numbers from given `arr`

In [3]:
# Input
arr = np.arange(30)

# Solution
arr = arr[arr%2==1]

# Print
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


### 3. Get the positions where elements of `a` and `b` match
(hint, refer [np.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html).)



In [4]:
# Input
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Solution
idx = np.where(a==b)

# Print
print(idx)

(array([1, 3, 5, 7]),)


### 4. Find the mean, median, standard deviation of iris's `sepallength` (1st column).

In [5]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
mu, med, std = sepallength.mean(), np.median(sepallength), sepallength.std()

# Print
print(mu, med, std)

5.843333333333334 5.8 0.8253012917851409


### 5. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.
(hint, refer [np.unique](https://numpy.org/doc/stable/reference/generated/numpy.unique.html).)

In [17]:
# Input
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)

# Solution
## Create an all True array
out = np.full(10, True, bool)

## Find the index positions of unique elements
unique_positions = np.unique(a, return_index = True)[1]

## Mark those positions as False
out[unique_positions] = False
print('Duplicate entrie: ', out)

Array:  [0 0 3 0 2 4 2 2 2 2]
[0 4 2 5]
Duplicate entrie:  [False  True False  True False False  True  True  True  True]


# Pandas Exercises!
Complete the solution code to have a desired output. 





### 6. Combine `ser1` and `ser2` to form a dataframe.

In [7]:
# Input
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

# Solution 
df = pd.DataFrame({'col1' : ser1, 'col2': ser2})

# Print
print(df.head())

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4


### 7. Check if `df` has any missing values.

In [8]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.head())

# Solution
print('\nIs there any missing value?:', df.isnull().values.any())

  Manufacturer    Model     Type  ...  Weight   Origin           Make
0        Acura  Integra    Small  ...  2705.0  non-USA  Acura Integra
1          NaN   Legend  Midsize  ...  3560.0  non-USA   Acura Legend
2         Audi       90  Compact  ...  3375.0  non-USA        Audi 90
3         Audi      100  Midsize  ...  3405.0  non-USA       Audi 100
4          BMW     535i  Midsize  ...  3640.0  non-USA       BMW 535i

[5 rows x 27 columns]

Is there any missing value?: True


### 8. Create a TimeSeries starting `2021-01-01` and 10 weekends (sundays) after that **having** random numbers as values?

In [19]:
# Solution
ser = pd.Series(pd.date_range('20210103', periods=10, freq="7D"))
print(ser)

0   2021-01-03
1   2021-01-10
2   2021-01-17
3   2021-01-24
4   2021-01-31
5   2021-02-07
6   2021-02-14
7   2021-02-21
8   2021-02-28
9   2021-03-07
dtype: datetime64[ns]


### 9. In `df`, compute the mean price of every fruit using grouping function.

In [30]:
# Input
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
# Solution
out = df.groupby('fruit').mean()
out.price

fruit
apple     1.666667
banana    8.000000
orange    5.666667
Name: price, dtype: float64

### 10. Join two dataframes `df1` and `df2` for intersection items on `use_id`.
For `df2`, please select only `use_id`, `platform`, `device` columns not all columns for merging.

In [50]:
# Input
base_path = 'https://raw.githubusercontent.com/shanealynn/Pandas-Merge-Tutorial/master/'
df1 = pd.read_csv(base_path + 'user_usage.csv')
df2 = pd.read_csv(base_path + 'user_device.csv')
# Solution
pd.merge(df1, df2[['use_id', 'platform', 'device']], on='use_id')

outgoing_mins_per_month  ...                  device
0                      21.97  ...                GT-I9505
1                    1710.08  ...                SM-G930F
2                    1710.08  ...                SM-G930F
3                      94.46  ...                   D2303
4                      71.59  ...                SM-G361F
..                       ...  ...                     ...
154                   198.59  ...                SM-G900F
155                   198.59  ...                SM-G900F
156                   106.65  ...              Moto G (4)
157                   344.53  ...                SM-G900F
158                    42.75  ...  Vodafone Smart ultra 6

[159 rows x 6 columns]